[package]
authors = ["HowManySmall"]
description = "Utilities related to threads."
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE"]
license = "MIT"
name = "howmanysmall/thread-utilities"                                                     # TODO: Convert to bura-games organization.
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "1.0.3"

[dependencies]
